name: eBills

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Install dependencies
        run: dotnet restore ./src/eBills.API/eBills.API.csproj

      - name: Build API project
        run: dotnet build ./src/eBills.API/eBills.API.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test eBills.sln

      - name: Publish
        run: dotnet publish ./src/eBills.API/eBills.API.csproj --configuration Release --output ./publish

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'your-app-name'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
